### ISSUE TITLE
Feature: Paging

### ISSUE THREAD

**Issue by berndca** [zippyui/react-datagrid#1]
Great grid component! What do you think about adding paging?

Thanks, Bernd

**Comment by zippyui-react** [comment]
Hi Bernd,

thanks for checking out our grid component. We're working on this and will notify you as soon as it's ready - hopefully very soon :)

**Comment by zippyui-react** [comment]
Just a notification that we're releasing the paging feature in the next couple of days

**Comment by bjrmatos** [comment]
you guys are awesome!
