### ISSUE TITLE
How to diable columns menu?

### ISSUE THREAD

**Issue by youngerheart** [zippyui/react-datagrid#105]
The columns menu which has class `z-show-menu` show in each column header, how can I disable them? It's no use in my project, thank~

**Comment by nikhilk78** [comment]
set withColumnMenu={false} should do it

Sent from my iPhone

On Oct 15, 2015, at 7:05 AM, Ge.Yang <notifications@github.com<mailto:notifications@github.com>> wrote:


The columns menu which has class z-show-menu show in each column header, how can I disable them? It's no use in my project, thank~

-

**Comment by radubrehar** [comment]
Thanks @nikhilk78 for being proactive. That's the correct prop!
