### ISSUE TITLE
Uncaught TypeError: Can't add property onMenuItemMouseOver, object is not extensible

### ISSUE THREAD

**Issue by lewinke** [zippyui/react-datagrid#107]
I am getting this error when I try and click to use the built in filters or column menu.  I am working on moving my app from 0.13 to 0.14.  I think it may have something to do with the React.createFactory here:

var ReactMenu = React.createFactory(require('react-menus'))

**Comment by ramakpuppala** [comment]
:+1: I am getting the same error as well with React 0.14. And as @lewinke suggested, its in the react-menus library

**Comment by AdaDoom3** [comment]
Getting the same issue

**Comment by ramakpuppala** [comment]
This issue is not reproducible if you run the app in production mode (NODE_ENV = production). In production mode everything works as designed. It seems to be breaking, only in development mode. Hope that helps in debugging.

**Comment by radubrehar** [comment]
Fixed in `2.0.1` just published to npm

**Comment by shaimo** [comment]
I'm getting the same error in react-dropdown-button (ver. 1.0.11). Maybe need the same fix there?
