### ISSUE TITLE
Filter Icon scaling

### ISSUE THREAD

**Issue by jhawthor** [zippyui/react-datagrid#109]
When I add the line "withColumnMenu={false}" the Filter Icon is huge.
![image](https://cloud.githubusercontent.com/assets/12467142/10597428/d849222e-76bc-11e5-98f2-153e0024415c.png)

I have customized the CSS file by replacing most background entries with transparent.  I have not removed any entry.  

Some other questions: 
  How can I color the text in the "Column Selection Box"?  I could not find a CSS entry for it?
  Can the Filter & Column selection Icons be replaced with custom icons?
  Can new columns be added to existing data set.  Right now I have to use the Id column to draw the Delete and Edit Icons.  I would prefer to have them in their own column, so 'Id' can can be viewed and sorted.

**Comment by jhawthor** [comment]
Fixed in size CSS.

**Comment by radubrehar** [comment]
Great!

**Comment by dcollinsf5** [comment]
Could you point me at the commit(s) that fixed this?  We can't update to react 14 currently, so I'd like to backport this fix to 1.2.15
