### ISSUE TITLE
Cannot duplicate sorting example...

### ISSUE THREAD

**Issue by jhawthor** [zippyui/react-datagrid#113]
I have tried to duplicate the sorting example and my code is nearly identical to the example with exception to my data set and comments (least I forget what I'm doing, as well as provide code for Doxygen to create source code documentation automatically), but I get an uncaught exception: "sortInfo is not define" What am I doing wrong? Any help is greatly appreciated.

```
/** Force the browser to run in strict mode.*/
"use strict";

// REGION: REQUIRE
/** using react.js */
var React = require('react');
/** using the react-datagrid for the table data with grommet styling*/
var DataGrid = require('react-datagrid');
/** using the sorty the multiple object sorting utility for sorting column data*/
var sorty    = require('sorty')


// REGION: VARIABLES
/** Prepare the column names and default widths for the table */
var columns = [
		{ name: 'Id', title: '#', width: 75},
		{ name: 'PackageName', flex: 1},
		{ name: 'ServerName', flex: 1},
		{ name: 'EventType', flex: 1 },
		{ name: 'Active', flex: 1 },
		{ name: 'CreateDate', width: 150 },
		{ name: 'UpdateDate', width: 150  }
];

/** Identify the sortable columns for the table */	
var SORT_INFO = [
	{ name: 'PackageName', dir: 'asc'}
];

// REGION: METHODS	
/** Perforn the sort using sorty */	
function sort(arr){
	return sorty(SORT_INFO, arr)
}

var ActiveEventList = React.createClass({
	propTypes: {
		activeEvents: React.PropTypes.array.isRequired
	},
	
	/** User clicked a header to toggle column sort, so perform the sort operation */
	handleActiveEventSortChange: function(data){
		SORT_INFO = sortInfo;
		data = sort(this.props.activeEvents)
		this.setState({})
	},
	
	/** User draged the column header, so perform column move */
	handleActiveEventColumnOrderChange: function (index, dropIndex){
		var col = columns[index]
		columns.splice(index, 1) //delete from index, 1 item
		columns.splice(dropIndex, 0, col)
		this.setState({})
	},
	
	render: function() {
		return (
			<div className="container">
				<DataGrid
					idProperty='Id'
					dataSource={this.props.activeEvents}
					columns={columns}
					style={{height: 400}}
					sortInfo={SORT_INFO}
					onSortChange={this.handleActiveEventSortChange}
					onColumnOrderChange={this.handleActiveEventColumnOrderChange}
				/>
			</div>
		);
	}
});

module.exports = ActiveEventList;
```

**Comment by nikhilk78** [comment]
Sort info structure is wrong.
The sorting handler function gives you the sortinginfo structure. In it you get which column is sorted and how. The "how" is given by dir.
The dir is  1 or -1 NOT 'asc' or 'desc' .
Before you give it to sorty needs asc or desc which you have to supply based on dir 1 or -1


Sent from my iPhone

On Oct 22, 2015, at 8:47 PM, jhawthor <notifications@github.com<mailto:notifications@github.com>> wrote:


I have tried to duplicate the sorting example and my code is nearly identical to the example with exception to my data set and comments (least I forget what I'm doing, as well as provide code for Doxygen to create source code documentation automatically), but I get an uncaught exception: "sortInfo is not define" What am I doing wrong? Any help is greatly appreciated.

/** Force the browser to run in strict mode.*/
"use strict";

// REGION: REQUIRE
/** using react.js */
var React = require('react');
/** using the react-datagrid for the table data with grommet styling*/
var DataGrid = require('react-datagrid');
/** using the sorty the multiple object sorting utility for sorting column data*/
var sorty    = require('sorty')


// REGION: VARIABLES
/** Prepare the column names and default widths for the table */
var columns = [
        { name: 'Id', title: '#', width: 75},
        { name: 'PackageName', flex: 1},
        { name: 'ServerName', flex: 1},
        { name: 'EventType', flex: 1 },
        { name: 'Active', flex: 1 },
        { name: 'CreateDate', width: 150 },
        { name: 'UpdateDate', width: 150  }
];

/** Identify the sortable columns for the table */
var SORT_INFO = [
    { name: 'PackageName', dir: 'asc'}
];

// REGION: METHODS
/** Perforn the sort using sorty */
function sort(arr){
    return sorty(SORT_INFO, arr)
}

var ActiveEventList = React.createClass({
    propTypes: {
        activeEvents: React.PropTypes.array.isRequired
    },

    /** User clicked a header to toggle column sort, so perform the sort operation */
    handleActiveEventSortChange: function(data){
        SORT_INFO = sortInfo;
        data = sort(this.props.activeEvents)
        this.setState({})
    },

    /** User draged the column header, so perform column move */
    handleActiveEventColumnOrderChange: function (index, dropIndex){
        var col = columns[index]
        columns.splice(index, 1) //delete from index, 1 item
        columns.splice(dropIndex, 0, col)
        this.setState({})
    },

    render: function() {
        return (
            <div className="container">
                <DataGrid
                    idProperty='Id'
                    dataSource={this.props.activeEvents}
                    columns={columns}
                    style={{height: 400}}
                    sortInfo={SORT_INFO}
                    onSortChange={this.handleActiveEventSortChange}
                    onColumnOrderChange={this.handleActiveEventColumnOrderChange}
                />
            </div>
        );
    }
});

module.exports = ActiveEventList;


-

**Comment by jhawthor** [comment]
Resolved. I was not passing the 'onClicked' event as a prop.
