### ISSUE TITLE
No way to remove "column removal" feature

### ISSUE THREAD

**Issue by AdaDoom3** [zippyui/react-datagrid#120]
I tried looking through the source and in tutorials, but I see no way to remove the ability to remove columns. Is this correct?

**Comment by nikhilk78** [comment]
What do you mean column removal? If you don't want the column menu which turns on or off column to see simply have prop withColumnMenu ={false}
If not, sorry I didn't understand what you meant

**Comment by JeffSanchez** [comment]
We're also interested in this detail, or better yet, the column frozen feature mentioned in the upcoming 1.3.0 release. Do we have any estimate for when 'column frozen' functionality may be available? (Or if it's already easily doable in the current latest version.) Thanks!

**Comment by AdaDoom3** [comment]
Thanks nikhilk, that is the prop i was looking for. Is there a place where there is just a simple list of supported props?
