### ISSUE TITLE
Unable to build With npm

### ISSUE THREAD

**Issue by Agilesolutionspk** [zippyui/react-datagrid#132]
I am attaching log file if someone can help.  Thanks
------------------------
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@3.3.12
3 info using node@v5.1.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle react-datagrid@1.2.15~predev: react-datagrid@1.2.15
6 silly lifecycle react-datagrid@1.2.15~predev: no script for predev, continuing
7 info lifecycle react-datagrid@1.2.15~dev: react-datagrid@1.2.15
8 verbose lifecycle react-datagrid@1.2.15~dev: unsafe-perm in lifecycle true
9 verbose lifecycle react-datagrid@1.2.15~dev: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\React\node_modules\react-datagrid\node_modules\.bin;C:\React\node_modules\.bin;C:\Users\Kamran\AppData\Roaming\npm;C:\Program Files\nodejs\;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\SourceGear\Common\DiffMerge\;C:\Program Files (x86)\Skype\Phone\;C:\Users\Kamran\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\nodejs\;C:\Users\Kamran\AppData\Local\atom\bin;C:\Users\Kamran\AppData\Roaming\npm
10 verbose lifecycle react-datagrid@1.2.15~dev: CWD: C:\React\node_modules\react-datagrid
11 silly lifecycle react-datagrid@1.2.15~dev: Args: [ '/d /s /c',
11 silly lifecycle   'NODE_ENV=production PORT=9090 webpack-dev-server --progress --colors --config  build/dev.config.js' ]
12 silly lifecycle react-datagrid@1.2.15~dev: Returned: code: 1  signal: null
13 info lifecycle react-datagrid@1.2.15~dev: Failed to exec dev script
14 verbose stack Error: react-datagrid@1.2.15 dev: `NODE_ENV=production PORT=9090 webpack-dev-server --progress --colors --config  build/dev.config.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:818:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid react-datagrid@1.2.15
16 verbose cwd C:\React\node_modules\react-datagrid
17 error Windows_NT 10.0.10240
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
19 error node v5.1.0
20 error npm  v3.3.12
21 error code ELIFECYCLE
22 error react-datagrid@1.2.15 dev: `NODE_ENV=production PORT=9090 webpack-dev-server --progress --colors --config  build/dev.config.js`
22 error Exit status 1
23 error Failed at the react-datagrid@1.2.15 dev script 'NODE_ENV=production PORT=9090 webpack-dev-server --progress --colors --config  build/dev.config.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the react-datagrid package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     NODE_ENV=production PORT=9090 webpack-dev-server --progress --colors --config  build/dev.config.js
23 error You can get their info via:
23 error     npm owner ls react-datagrid
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

----------------------------

**Comment by radubrehar** [comment]
The problem is you're using windows and the build script has an env var it's using in UNIX style (NODE_ENV)

**Comment by Agilesolutionspk** [comment]
Thank you for pointing out.  If anyone knows windows equivalent or a way to create same environment on windows? Please give some help.

**Comment by stevenpietzsch** [comment]
I managed it like this in Windows:
```
"build": "set NODE_ENV=production npm run lib ...
```

**Comment by Agilesolutionspk** [comment]
Thank you.

**Comment by Agilesolutionspk** [comment]
Thank you for the help.
