### ISSUE TITLE
Support nested data structure

### ISSUE THREAD

**Issue by tbrd** [zippyui/react-datagrid#136]
Currently it is not possible to render a column based on a nested data structure. E.g.:
```
[
    {
        id: '1022',
        name: 'Victoria Station',
        address: {
            streetName: 'Victoria Street',
            city: 'London',
            postCode:'SW1E 5ND'
        },
    }
]
```

In most situations it is possible to flatten the data, but this is not always the case. 

Proposed solution:
split name on '.' and use parts to access the data

**Comment by radubrehar** [comment]
Just use a `render` function on the column.

**Comment by radubrehar** [comment]
See https://github.com/zippyui/react-datagrid/issues/54#issuecomment-107417278

**Comment by tbrd** [comment]
Ah, I see, thank you :)

**Comment by eminaz** [comment]
If in this case I want a column for "address.streetName" and a column for "address.city", is it possible?

**Comment by radubrehar** [comment]
See https://github.com/zippyui/react-datagrid/issues/54#issuecomment-107417278
