### ISSUE TITLE
Create Typescript defintions for react-datagrid.

### ISSUE THREAD

**Issue by stephenjelfs** [zippyui/react-datagrid#137]

**Comment by stephenjelfs** [comment]
Done.

**Comment by RikkiGibson** [comment]
Any chance on an update for this to react-datagrid 2.0.2?

**Comment by radubrehar** [comment]
Can you be more explicit please? What exactly do you expect from our part? We are happy to help.

**Comment by stephenjelfs** [comment]
@RikkiGibson I initially created the definitions for react-datagrid for DefinitelyTyped. However, in the end, I decided to switch to Fixed-Data-Table so am currently only maintaining the definitions for the latter. Maybe you could switch to Fixed-Data-Table too? It's up-to-date definitions work nicely with the awesomeness that is Typescript :)

**Comment by radubrehar** [comment]
@stephenjelfs thanks for the updates.

We're in the middle of a complete rewrite - in fact, almost done, and will release a stable version very soon, that is going to close a lot of the issue reported.

**Comment by stephenjelfs** [comment]
@RikkiGibson FYI I switched to Fixed-Data-Table because we have very large datasets and we only wanted to load the rows that were currently visible (or buffered).  This could be achieved because their API allows you define a "rowCount" and a function to return results per-row (instead of all rows in bulk).  If the react-datagrid also supported this, that would be a great reason to switch back.

**Comment by radubrehar** [comment]
Sure thing, thanks for pointing that out!
Yes, we're also including virtual rendering, so only render the visible rows - which allows for very large data sets. But yes, you need to pass in the whole array for now - so we're introducing a function to request & return a specific row, by index, only when needed. We were thinking of doing this anyway, but now that it's being reported, will get this in asap.

PS: A good feature we have, that's a plus over fixed-data-table is normal browser scrollbars. Personally I prefer those over simulated scrollbars. And the performance we offer will be the same.

Thanks

**Comment by stephenjelfs** [comment]
@radubrehar That would be great. Once this is added I'll take some time to try it out--and update the Typescript definitions in the process. Thanks.

**Comment by RikkiGibson** [comment]
Basically, I was dealing with some quirks related to importing the library, importing the CSS, accessing some of the interfaces not directly exported in the require() call like ReactDataGrid.Column. I looked and saw an apparent mismatch in the library version named in the TypeScript definitions file and in my project.json. I ascribed some of the problems I experienced in getting it set up to that mismatch.

I’ll try and take a look at Fixed Data Table— I set it aside when Facebook’s examples failed to work in IE, and inserting a polyfill into their example site made it behave seemingly quite erratically and fail to scroll anyway.

Thanks a lot for the prompt response and the advice.

**Comment by keawade** [comment]
The definitions haven't been updated since the initial commit in December. Can we get them updated so we can use this package with TypeScript again?

**Comment by stephenjelfs** [comment]
@keawade I'm not sure if anyone is actively maintaining these now (since I switched to working on a new project).  I suggest you just create your own custom copy of the typings to get things working quickly.  Then, if you do later decide to push your changes to definitively typed, I promise to review and give the thumbs-up so it's merged quickly.
