### ISSUE TITLE
Add compiled css to dist

### ISSUE THREAD

**Issue by mikechau** [zippyui/react-datagrid#14]
For folks who do not use `styl`, I think it would be convenient if you guys could compile the default css and include it with `dist`.

**Comment by zippyui-react** [comment]
You can use index.css (compiled from index.styl) from the root folder, but yes, it is a good idea to include it in the dist folder as well. We'll also include a index.min.css in the dist folder. Thanks for the notice!

**Comment by mikechau** [comment]
Awesome thanks!

**Comment by zippyui-react** [comment]
We've added the files to the dist folder (both normal & minified )
