### ISSUE TITLE
ie11 flex issue

### ISSUE THREAD

**Issue by degr** [zippyui/react-datagrid#145]
I have ie 11.0.9600.18125, and there is nothing displayed inside of grid. It can be healed by adding this stlyle (according to https://developer.mozilla.org/en/docs/Web/CSS/flex , browser support part, 3rd point)

```
.z-inner{
flex-basis: auto;
}

**Comment by radubrehar** [comment]
Thanks @degr. Can you send a PR please?

**Comment by degr** [comment]
I create PR, but I never work with stylus, so, I can't test changes. By the way, think it is hard to do something wrong there.

**Comment by radubrehar** [comment]
Have you tested the fix to make sure everything works okay? See https://github.com/zippyui/react-datagrid#contributing for instructions on how to test the grid locally on your machine.

**Comment by radubrehar** [comment]
What's the status of the issue? Is the current behavior correct on IE, or is your fix the correct solution?

**Comment by degr** [comment]
I will update PR now.
