### ISSUE TITLE
React Elements in columns

### ISSUE THREAD

**Issue by berndca** [zippyui/react-datagrid#15]
I would like to put links, buttons etc into columns of the datagrid. I tried the example, but it appears that I can not return a React element in the column render function. 

Please advise.
Thanks, Bernd

**Comment by zippyui-react** [comment]
You can use react elements. For example, the config of a column can be
```jsx
{
    name: 'index',
    render: function(v){
        return <span style={{fontWeight: 'bold'}}>{v}</span>
    }
}
```

If you've tried on the online live editor, on our example site, and got an error, it may be due to a bug manifesting sometimes in the live editing feature. Was this the case? Or have you tried an example on your local machine and didn't work?

**Comment by berndca** [comment]
I tried the online editor and used the javascript notation React.createElement("p", null, v) instead of jsx.

**Comment by zippyui-react** [comment]
Can you try that again, for example on the  http://zippyui.github.io/react-datagrid/#/examples/custom-column-rendering.
But better to try it locally, it will certainly work.

**Comment by berndca** [comment]
Thanks, I got it to work online by using copy/paste to avoid issues during typing.

Thanks, Bernd

**Comment by zippyui-react** [comment]
Great!
As a bonus, we've just released 1.1.3 with support for remote data source and pagination.

**Comment by berndca** [comment]
Ecxellent! 

My only concern about the new remote data source is the additional dependencies. Would you consider offering the remote data feature as a plugin?

**Comment by radubrehar** [comment]
Yes, we will probably consider that in a near future. Let's see the
community reaction and the demand for this. Generally, in real-life apps
people use pagination, though they may use different things for data
loading (we polyfill the fetch method in browsers)

--
http://radubrehar.ro
http://bibliaonline.ro
http://jslog.com

**Comment by berndca** [comment]
I'm using pouchdb to connect to the backend, so I wont be able to use the build in data source. I like the fact that I can wrap the pouchdb response in a function and pass it to the datagrid.

**Comment by mikechau** [comment]
Also, if you need to reference data from other columns, you can add another argument to render:

```js
{
  name: 'actions',
  render: function(v, row) {
    return (<a href={row.id}>View</a>);
  }
}
```

**Comment by berndca** [comment]
Cool, that's very useful.
