### ISSUE TITLE
horizontal scrollbar position does not move

### ISSUE THREAD

**Issue by shedali** [zippyui/react-datagrid#170]
If the window is resized so that the table width is larger than the container, the horizontal scrollbar shows. 

http://zippyui.com/react-datagrid/#/examples/large-data-array

Dragging the scrollbar or using shift+scroll causes the table to move horizontally. However, the position of the scrollbar does not move in Chrome version 47.0.2526.111. It works in Firefox and Internet explorer

**Comment by bogdanpetru** [comment]
@shedali Thank you for reporting. 
There is an open issue on this bug #156.
