### ISSUE TITLE
How can I completely hide the header?

### ISSUE THREAD

**Issue by cheton** [zippyui/react-datagrid#177]
I'd like to display only the data without showing headers in my DataGrid. Is there any way to do this without using CSS?

**Comment by radubrehar** [comment]
Right now you have to use css. We're very close to publishing v3 of the datagrid, which is much improved, and will have a `header: false` property.

**Comment by cheton** [comment]
I just found a workaround solution by setting headerFactory to an empty div:
```
<DataGrid
    headerFactory={() => <div />}
/>
```

Looking forward to v3 of datagrid. Thanks.
