### ISSUE TITLE
Cannot Access documentation

### ISSUE THREAD

**Issue by sravanrekandar** [zippyui/react-datagrid#179]
http://zippyui.github.io/react-datagrid
Its been redirected to http://zippyui.com/react-datagrid

response: 

404 Not Found

nginx/1.4.6 (Ubuntu)

**Comment by radubrehar** [comment]
Thanks for pointing that out! We've just launched our website and that's broken the links. We're fixing this, thanks.

**Comment by radubrehar** [comment]
Fixed! Thanks for patience

**Comment by sravanrekandar** [comment]
Thanks!
