### ISSUE TITLE
the scrollbar can not scroll in Chrome

### ISSUE THREAD

**Issue by airwin** [zippyui/react-datagrid#19]
Firefox is OK but Chrome(version 42.0.2311.11 m) can't scroll.

**Comment by zippyui-react** [comment]
Can you please update to 1.1.6, recently published on NPM?

Are you trying the online examples at http://zippyui.github.io/react-datagrid/#/examples/basic? We'd live to know how to reproduce that. Thanks for helping

**Comment by airwin** [comment]
I tryed this example [column-resizing](http://zippyui.github.io/react-datagrid/#/examples/column-resizing). Chrome both in win&mac can not act the horizontal scrolling.

**Comment by airwin** [comment]
hey @zippyui-react. I notice that the real reason is the horizontal scrolling bar is difficult to focus with mouse, but when I hover on it carefully, it can be drag and scrolling successful.

**Comment by zippyui-react** [comment]
On a Mac, the scrolling is done with the trackpad, so no need to focus/drag the scrollbar. On a Windows machine, I cannot reproduce the issue on Chrome.
For easier horiz scrolling, you can always use shift+wheel/trackpad

**Comment by koustuvsinha** [comment]
@airwin yep confirmed horizontal scrolling for the [column-resizing](http://zippyui.github.io/react-datagrid/#/examples/column-resizing) is not working in Chrome 42.0.2311.90 m Windows & 64Bit, BUT only on the first render. When I resize any column by even a little amount the horiz scroll function is working again!

**Comment by zippyui-react** [comment]
Thanks for reporting. Definitely will be looking into it, since it can be a blocker for many people using the grid.

**Comment by airwin** [comment]
@koustuvsinha I tried and that's true, after some operations it works. May just a little problem of chrome..

**Comment by zippyui-react** [comment]
Yes, it's a Chrome issue, but we're working on avoiding that. I notice that if in the example page I hit F5, the issue dissapears in my case. It's a display issue chrome is having, since we're using the scrollbars in an unconventional way (when you scroll, you're not actually scrolling the grid, but a hidden div, and grid content gets updated - for vscroll, or translated - for hscroll)

**Comment by zippyui-react** [comment]
@airwin  can you please check now and see if it's working? Took me a few hours to nail it down :) but hopefully we've managed to workaround the chrome flex display issue

**Comment by airwin** [comment]
@zippyui-react I updated to the latest version and the problem disappeared. Nice Job!

**Comment by zippyui-react** [comment]
Great to hear that!

**Comment by anil1712** [comment]
Hi,
I am using the latest version, still I am getting the same issue. Horizontal Scroll bar not appeares in Windows Google chrome browser.

Thanks
