### ISSUE TITLE
Sorting in demo not working

### ISSUE THREAD

**Issue by oskip** [zippyui/react-datagrid#193]
http://zippyui.com/react-datagrid/#/examples/sorting

When clicking on column header it seems like dragging is starting immediately instead of onClick sorting behaviour.
Browser: Chrome 49.0.2623.110

**Comment by cpswaim** [comment]
I'm seeing this same issue in Chrome 52.0.2743.116.

If I disable reordering, I can sort, but I can't have both enabled. Also seeing the same in the demo (when I click, it attempts to drag the column rather than sorting).

Was there a fix or resolution for this?
