### ISSUE TITLE
Feature: Save/Load/Get/Reset grid state

### ISSUE THREAD

**Issue by eduardotang** [zippyui/react-datagrid#2]
great grid, it would be very nice if you can add this in the upcoming release.

**Comment by zippyui-react** [comment]
Hi and thanks for using `react-datagrid`. I suppose you mean you want to restore for example column visibility/size from another point in time. Eg: if the user opens up an UI and plays around with column sizes/visibility, then navigates somewhere else and afterwards comes back to the same UI, you want to display it in the same state as it was left.
Is this correct?
We're going to release an example and proove how this can be easily done. Let us know your thoughts

**Comment by eduardotang** [comment]
Actually what i am planning to do is to have multiple states which will be stored in the server.
User can quickly switch between multiple combination of visible/hidden columns.
or user can add new combination of visible/hidden columns.

so i am thinking maybe something like below for setting the state, but for retrieving, i am not sure,sinc i am still new to react

state = [ 
   { name:'cola' , hidden:true } ,
   { name:'colb' , hidden:false }
]
<DataGrid
    ....
    state = {state}
     .... />

**Comment by zippyui-react** [comment]
Will be adding a new example on our site tomorrow with this, so you can play with it :)

**Comment by eduardotang** [comment]
thx....

**Comment by zippyui-react** [comment]
Please see http://zippyui.github.io/react-datagrid/#/examples/restore-grid-state for an example and let us know if this is what you intend.

NOTE: in the example, at any point, the grid state is found in GRID_INFO variable, so it's always up to date.

**Comment by eduardotang** [comment]
yeah, neat and clear
thx :)
