### ISSUE TITLE
Sortable Currency Values

### ISSUE THREAD

**Issue by philster** [zippyui/react-datagrid#203]
How can I render a currency field while allowing it to be sortable by numeric value?
```
var sortInfo = [
  { name: 'itemName', dir: 'asc' },
  { name: 'price', dir: 'desc' }
];
var sorty = require('sorty');
 
function sort(arr) {
  return sorty(sortInfo, arr);
}
 
function onSortChange(info) {
  sortInfo = info;
  data = sort(data);
  //now refresh the grid
}

var data = [
  { id: 1, itemName: 'Item A', price: '0.99' },
  { id: 2, itemName: 'Item B', price: '5.95' },
  { id: 3, itemName: 'Item C', price: '1.99' },
  { id: 4, itemName: 'Item D', price: '19.99' },
  { id: 5, itemName: 'Item E', price: '199' }
];
var columns = [
  {
    name: 'itemName',
    title: 'Item Name'
  },
  {
    name: 'price',
    render: function (v) { return '$' + v; },
    title: 'Item Price',
    type: 'number'
  }
];
...
<DataGrid
  idProperty="id"
  dataSource={data}
  columns={columns}
  onSortChange={onSortChange}
  sortInfo={sortInfo}
  />
```

I noticed it seems to sort the `price` column lexicographically, which is not what I expect.

Thanks!

**Comment by nikhilk78** [comment]
I  have done this using lodash for integers and will put exact code in few hours, but I am sure sorty takes anonymous function which would use parseFloat and return true or false ( based on ascending or descending )



Sent from my iPhone

On May 3, 2016, at 6:28 PM, Phil Wee <notifications@github.com<mailto:notifications@github.com>> wrote:


How can I render a currency field while allowing it to be sortable by numeric value?

var sortInfo = [
  { name: 'itemName', dir: 'asc' },
  { name: 'price', dir: 'desc' }
];
var sorty = require('sorty');

function sort(arr) {
  return sorty(sortInfo, arr);
}

function onSortChange(info) {
  sortInfo = info;
  data = sort(data);
  //now refresh the grid
}

var data = [
  { id: 1, itemName: 'Item A', price: '0.99' },
  { id: 2, itemName: 'Item B', price: '5.95' },
  { id: 3, itemName: 'Item C', price: '1.99' },
  { id: 4, itemName: 'Item D', price: '19.99' },
  { id: 5, itemName: 'Item E', price: '199' }
];
var columns = [
  {
    name: 'itemName',
    title: 'Item Name'
  },
  {
    name: 'price',
    render: function (v) { return '$' + v; },
    title: 'Item Price',
    type: 'number'
  }
];
...
<DataGrid
  idProperty="id"
  dataSource={data}
  columns={columns}
  onSortChange={onSortChange}
  sortInfo={sortInfo}
  />


I noticed it seems to sort the price column lexicographically, which is not what I expect.

Thanks!

-

**Comment by radubrehar** [comment]
Just pass in numbers and use column.render to do the formatting.

**Comment by philster** [comment]
Ok thanks!
