### ISSUE TITLE
Compiled stylesheets?

### ISSUE THREAD

**Issue by hakunin** [zippyui/react-datagrid#216]
Hi,
I can't get my webpack to resolve the paths pointing at other modules (I am using the v3).
It would be super nice if there was a compiled stylesheet in a dist directory.

**Comment by radubrehar** [comment]
We'll provide an index.css sometime tomorrow or the day after. I'll get back to you as soon as possible.

**Comment by hakunin** [comment]
Thank you! I've been trying to compile it manually yesterday and it didn't look like I've succeeded :)

**Comment by radubrehar** [comment]
v `3.0.4-beta` is on npm, with the compiled stylesheets. You can require them.

```jsx
import DataGrid from 'react-datagrid'
import 'react-datagrid/index.css' //to get the base styles + the default theme
```

or you can do

```jsx
import 'react-datagrid/base.css'  // to only get the base styles
import 'react-datagrid/theme/default.css'  //to only get the default theme styles - without the base.css
```

**Comment by hakunin** [comment]
Thanks! Thats such a great news! I was hoping to be able to use the v3, thanks!

**Comment by radubrehar** [comment]
We've just started heavy work on v3 to have it publicly launched, so expect improvements at a rapid pace!
