### ISSUE TITLE
[V3] Custom render not rendering cell size properly

### ISSUE THREAD

**Issue by hakunin** [zippyui/react-datagrid#220]
V3 custom rendering seems to have an issue. In 3.0.4-beta it renders fine, in higher versions (I tried 10+) it doesn't.

```
      },{
        name: 'price',
        title: 'Cena',
        width: 90,
        textAlign: 'right',
        render: money,
        type: 'number',
      },{
```

```
var money = function(value) {
  if (!value) {
    return <span>0 kč</span>
  }
  if (value.value >= 10) {
    return <span>{Math.round(value.value)} kč</span>
  } else {
    return <span>{(value.value || 0)} kč</span>
  }
}
```

![screenshot 2016-06-17 15 18 36](https://cloud.githubusercontent.com/assets/65846/16151774/1550de6e-349f-11e6-9ec3-d0ad01752986.png)

**Comment by hakunin** [comment]
There is missing FlexItem wraper.
![screenshot 2016-06-17 15 27 03](https://cloud.githubusercontent.com/assets/65846/16152016/01496142-34a0-11e6-961f-1e8a654f8a90.png)

**Comment by radubrehar** [comment]
Please use the latest v3 on npm `npm i --save react-datagrid@beta` - we found the bug this week and it should be fixed now.

**Comment by hakunin** [comment]
"react-datagrid": "3.0.15-beta", still produces the issue

**Comment by radubrehar** [comment]
`3.0.18-beta` is out with the fix!
The `render` function is called with `{ value, data, cellProps }` so be sure to use it properly:

```javascript
const money = ({ value, data, cellProps }) => {
  if (!value) {
    return <span>0 kč</span>
  }
  if (value >= 10) {
    return <span>{Math.round(value.value)} kč</span>
  }
  return <span>{(value || 0)} kč</span>
}
```
