### ISSUE TITLE
Missing react-flex form package.json

### ISSUE THREAD

**Issue by hakunin** [zippyui/react-datagrid#222]
While investigating why heroku won't deploy, I noticed that `react-flex` dependency doesn't seem to be included in the package.json
```
remote:        npm ERR! Linux 3.13.0-85-generic
remote:        npm ERR! argv "/tmp/build_31008b9f1d0c2dd86b94f5810dac6426/.heroku/node/bin/node" "/tmp/build_31008b9f1d0c2dd86b94f5810dac6426/.heroku/node/bin/npm" "install"
remote:        npm ERR! node v4.2.0
remote:        npm ERR! npm  v3.3.6
remote:        npm ERR! path /tmp/build_31008b9f1d0c2dd86b94f5810dac6426/client/node_modules/react-flex/node_modules/react-class
remote:        npm ERR! code ENOENT
remote:        npm ERR! errno -2
remote:        npm ERR! syscall rename
remote:        
remote:        npm ERR! enoent ENOENT: no such file or directory, rename '/tmp/build_31008b9f1d0c2dd86b94f5810dac6426/client/node_modules/react-flex/node_modules/react-class' -> '/tmp/build_31008b9f1d0c2dd86b94f5810dac6426/client/node_modules/react-datagrid/node_modules/react-class'
remote:        npm ERR! enoent This is most likely not a problem with npm itself
remote:        npm ERR! enoent and is related to npm not being able to find a file.
remote:        npm ERR! enoent
```

**Comment by radubrehar** [comment]
I'm looking into `package.json` and everything seems to be fine. Also looking into the `package.json` of `react-flex` to have the dependency for `react-class` as well, and it's also fine.

Are you using the v3 version (`npm i --save react-datagrid@beta`)?
Can you provide more context so we can solve the above error?
You could try `rm -fr node_modules` - amazingly how often it solves problems :(

**Comment by hakunin** [comment]
This is for the v2, I reverted as v3 isn't working.

**Comment by radubrehar** [comment]
We're not using `react-flex` in v2, so you probably used v3 first and then reverted to v2 without clearing node_modules.

Expect new releases on v3 next week as we're actively pushing new features on it, including locked columns, etc. Hope you'll enjoy using it, it's already way better than the old v2, which has a number of scrolling issues.

**Comment by hakunin** [comment]
I found that I included when I tried to fix the flex issue, my bad! Hopefully I can use the v3 soon.
