### ISSUE TITLE
"npm run dev" error on windows - React is not defined

### ISSUE THREAD

**Issue by trbgroupm** [zippyui/react-datagrid#225]
Hi there,

I've run "npm run dev" and everything seems to startup and run fine. When I visit http://localhost:9090/ in my browser (chrome or firefox) nothing shows up, and in the console it has the following error:

bundle.js:654 Uncaught ReferenceError: React is not defined

Is this expected? Is there something else I need to do to get things working?

I'm running on windows, and I've already changed the package.json scripts to work on windows. i.e.
from:
"NODE_ENV=production PORT=9090 webpack-dev-server --progress --colors --config  build/dev.config.js"
to:
"set NODE_ENV=production && set PORT=9090 && webpack-dev-server --progress --colors --config  build/dev.config.js"

**Comment by radubrehar** [comment]
Please check out the `v3` branch and run
```sh
$ npm i
$ npm run dev
```

goto `localhost:9191` and you should be fine.

The `v3` branch contains the new version of the grid, which is a major improvement from the current `master` branch, with quite a few new features in the works

**Comment by trbgroupm** [comment]
I'd prefer to get it working on `master`, since that's what we're using in production. But anyway I tried it with `v3` and that all builds fine. Thanks.
