### ISSUE TITLE
Remote datasource: JSON format customizing

### ISSUE THREAD

**Issue by gijs** [zippyui/react-datagrid#24]
Hi!

Thanks for this great component!

I'm trying add a remote datasource, which is a REST API. This API returns an array which is wrapped in a 'results' object:
```
{"results":[{
   "wns_oms": "C2yazfs[u
   ...
]}
```

When I strip off the results and just return the [], it works.
However, when I use the actual API, it seems unable to parse.

This is the dataSource section which should return a promise. I'm returning data.results on success, but nothing happens:

```
  dataSource: function(query) {
    return $.ajax({
        url: 'http://localhost:8081/api/'
        // url: 'http://localhost:8081/static/dummy.json'
      })
      .success(function(data) {
        console.log('data', data);
        return data.results;
      });
  },  
```

Am I doing this wrong?

thx!

Gijs

**Comment by gijs** [comment]
My bad; The jQuery docs told me about the dataFilter method:

```
  dataSource: function(query) {
    return $.ajax({
       contentType: "application/json",
       dataType: "json",
       dataFilter: function(f) { // Needed to sanitize the API response
        return JSON.stringify(JSON.parse(f).results);
       },
       url: 'http://localhost:8081/api/'
      });
  },  
```

This does the trick in our case.

**Comment by zippyui-react** [comment]
jquery returns a Deferred object, which is partly compatible with the Promise API

So, yes, you can use the code you mentioned, or you can do

```js
 dataSource: function(query) {
    return $.ajax({
       contentType: "application/json",
       dataType: "json",
       url: 'http://localhost:8081/api/'
      })
    .then(function(response){
        return response.results
    })
  }
```
(code above not tested)
which is in my opinion more elegant.

If you need the pagination feature/toolbar, you will need to do some restructuring, since the grid expects and object with {data,count} keys, count being the remote count

```js
 dataSource: function(query) {
    return $.ajax({
       contentType: "application/json",
       dataType: "json",
       url: 'http://localhost:8081/api/?pageSize='+query.pageSize+'&skip='+query.skip
      })
    .then(function(response){
        return {
            data: response.results,
           count: respone.resultsLength
       }
    })
  },  
```
