### ISSUE TITLE
readme instructions lead to errors on some platforms (e.g. windows 10)

### ISSUE THREAD

**Issue by sfthurber** [zippyui/react-datagrid#247]
[npm-debug.txt](https://github.com/zippyui/react-datagrid/files/476816/npm-debug.txt)

C:\Users\User\react-datagrid>npm run dev

> react-datagrid@2.1.1 dev C:\Users\User\react-datagrid
> NODE_ENV=production PORT=9090 webpack-dev-server --progress --colors --config  build/dev.config.js

'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! react-datagrid@2.1.1 dev: `NODE_ENV=production PORT=9090 webpack-dev-server --progress --colors --config  build/dev.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-datagrid@2.1.1 dev script 'NODE_ENV=production PORT=9090 webpack-dev-server --progress --colors --config  build/dev.config.js'.
npm ERR! This is most likely a problem with the react-datagrid package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     NODE_ENV=production PORT=9090 webpack-dev-server --progress --colors --config  build/dev.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-datagrid
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls react-datagrid
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\User\react-datagrid\npm-debug.log

C:\Users\User\react-datagrid>

**Comment by stevenpietzsch** [comment]
Please look at this: #132

**Comment by sfthurber** [comment]
thanks!
