### ISSUE TITLE
Is it possible to listen double click event on the cell and show textinput or other element ?

### ISSUE THREAD

**Issue by lawlessnut** [zippyui/react-datagrid#256]

**Comment by holly-juan** [comment]
I think you can rewrite the source code,  I solve it by adding code in render function in Cell file 
props.onDoubleClick = this.setEdit.bind(this, props.column, keyId);

**Comment by mtham8** [comment]
@holly-juan Could you elaborate on your implementation? How does this.setEdit look like? Thanks!

**Comment by lawlessnut** [comment]
@holly-juan for me the way i have done is pass custom render for the column render function.
This will edit data and will bind edited data to actual data you passed to your datagrid.

`
// columns needs to be passed to your datagrid.
var columns = [
            { name: "selected", title : "", render : this.checkboxRender},
            { name:"tagId",     title : "Tag ID" ,render : this.renderTextInput},
            { name:"isActive",  title : "Is Active"},
            { name:"position",  title : "Position"},
            { name:"offset",    title : "offset"},
            { name:"tagG",      title : "Tag Group"},
            { name:"entity_name", title : "Entity Name"},
            { name:"battery",   title : "Status"}
        ];

renderTextInput : (value,data,cellProps){
        return (<EditableRender nValue={value}
                                nMainAppId={"mainAppId"}
                                nRowKey={"tagId"}
                                nRowData={data} />)
    }
}



var EditableRender = React.createClass({

    /*
    * This component will also fire customEvent name renderValueUpdate application level.
    * Listen event using document.getElementById("{your application id}").addEventListener("renderValueUpdate",{handler},false)
    *
    *
    * @nValue       : current value of the cell
    * @nValueType   : value type can be string,number,array
    * @nRowData     : row data of the grid table
    * @nMainAppId   : is main app id i.e ID of the where you render your React application please look in to
     *          first child of the body to find your App Id .*/

    propTypes : {
        nValue      : React.PropTypes.any.isRequired,
        nValueType  : React.PropTypes.string,
        nRowData    : React.PropTypes.object.isRequired,
        nMainAppId  : React.PropTypes.string.isRequired,
        nRowKey     : React.PropTypes.string.isRequired
    },


    getInitialState: function () {
        return {
            nValue : 0
        }
    },

    componentWillReceiveProps : function(nextProps){
        this.setState({
                nValue : nextProps.nValue
            })
    },
    render: function () {
        return (
            <div ref="renderRef" className="hbox" onDoubleClick={this.handleRenderDBClick}>
                <span >{this.props.nValue}</span>
                <span className="hidden">
                    <TextField defaultValue={this.props.nValue} ref="nTextRenderRef" style={{width:80}}/>
                    <IConBtn onClick={this.handleRenderDBClick}>
                        <FontIcon className="fa fa-save fa-lg"/>
                    </IConBtn>
                </span>
            </div>
        )
    },

    handleRenderDBClick : function (e) {
        var els = this.refs.renderRef.childNodes;
        els[0].classList.toggle("hidden");
        els[1].classList.toggle("hidden");
        if (e.type === "click") {
            if (this.props.nRowData.hasOwnProperty(this.props.nRowKey)) {
                this.props.nRowData[this.props.nRowKey] = this.refs.nTextRenderRef.getValue();
             } else {
                throw error(" nRowData props doesn\'t contain key " + this.props.nRowKey);
            }

        }
    }

});




`

**Comment by emorling** [comment]
@lawlessnut thanks for sharing this. Does it edit the underlying data, so that filtering and sorting works correctly with edited data?

**Comment by lawlessnut** [comment]
It does work as it is cause data get bind both ways.
