### ISSUE TITLE
Column Resizing won't work.

### ISSUE THREAD

**Issue by KevinMongiello** [zippyui/react-datagrid#266]
I have added the onColumnResizing prop to the DataGrid with the function exactly how the examples show.  I now get the correct cursor when hovering the edges of columns, and a line shows to display the new col width when dragging a column. However, nothing happens when unclicking. Using react-datagrid v 2.1.2 in redux

**Comment by huumanoid** [comment]
This may be helpful:
`firstCol` from example is exactly the column from `props.columns`.
Yes, it's `props.columns[n]`.
So, if you are rebuilding `columns` every time you rendering `DataGrid`, resize won't work.

As for me, i'm storing sizes in my wrapper instead:
```js
this.setState({ 
  sizes: assignIn({}, this.state.sizes, { 
    [firstCol.name]: firstSize 
  }) 
})
```

and setting col's sizes when building `props.columns`:
```js
map(columns, (column) => {
  const size = this.state.sizes[column.name]
  if (size !== undefined) {
    return assignIn({}, column, { width: size })
  }
  return column
})
```

Of course, if you don't use wrapper, you may store sizes anywhere you want.

Hope this helps, looking for response from you.

**Comment by KevinMongiello** [comment]
Ah that makes sense, I will try to fix my code later tonight and let you know if it works! thanks @huumanoid
