### ISSUE TITLE
How to disable filtering, ordering for a separate column.

### ISSUE THREAD

**Issue by AlexandrSeleznev** [zippyui/react-datagrid#29]
Nice grid! 
I would like to disable ordering and filtering for some columns in my grid. Is it possible?
Can I do it like that
```javascript
columns = [ {name: 'id', title: 'ID', filter: false, order: false}, ...]
```

**Comment by zippyui-react** [comment]
Yes, have a look at our basic example

http://zippyui.github.io/react-datagrid/#/examples/basic

This does not have sorting/fildering

Hope you find the grid useful :)

**Comment by AlexandrSeleznev** [comment]
In the example is the filtering disabled for all columns. I'm looking for the possibility to disable the filtering just for one column, in my case for column 'Start'.
```javascript
columns = [ 
  {name: 'id', title: 'ID'}, 
  {name: 'name', title: 'Name'},
  {name: 'start', title: 'Start'} 
};

**Comment by zippyui-react** [comment]
Sorry, haven't the issue thoroughly. Yes, to disable for a column only, specify `filterable: false`

**Comment by zippyui-react** [comment]
PS: The `renderFilterField` method on the column  is subject to change in future versions of the grid

**Comment by AlexandrSeleznev** [comment]
It's where I'm looking for, thanks a lot!

**Comment by zippyui-react** [comment]
We're glad this solved your problem & hope you like the grid.
Check out other React components as well in our repo (maybe you'll find the [datepicker](http://zippyui.github.io/react-date-picker/) useful as well)

**Comment by AlexandrSeleznev** [comment]
I've tried to use renderFilterField option to add some help text to filter-input-field without success. I do it like that:
```javascript
renderFilterField: function(fieldProps, t) {
            return (<input placeholder='0..10' type='text' defaultValue={fieldProps.defaultValue}/>);
 }},
```
I get the placeholder into the field but it breaks the filter functionality. 
Could you explain me please what I'm doing wrong? Is there another way to add help-text into the input field?

**Comment by zippyui-react** [comment]
The simplest is to add `placeholder` to `fieldProps`.

Eg:
```
renderFilterField: function(fieldProps){
    fieldProps.placeholder = '0..10'
    return <input {...fieldProps} />
}
```

or you can do 
```
renderFilterField: function(fieldProps){
    return <input placeholder="0..10" {...fieldProps} />
}
```
`fieldProps` contains an `onChange` handler, and in your example, and since you are not using it, it breaks the filtering. If you choose not to pass in the default `fieldProps` to the rendered `<input />`, you have to specify your own `onChange` and perform the filtering yourself

**Comment by AlexandrSeleznev** [comment]
It's works. spasibo, the code:

```javascript
... ,
renderFilterField: function(fieldProps){
    return (<input placeholder='0..10'
                onChange={fieldProps.onChange}
                defaultValue={fieldProps.defaultValue}
                autoFocus={fieldProps.autoFocus}
                onKeyUp={fieldProps.onKeyUp} />);
},
.......
```

**Comment by zippyui-react** [comment]
Why do you explicitly specify all props?
```jsx
<input {...fieldProps} />
```
is valid React/jsx code.

**Comment by zippyui-react** [comment]
It's less error prone to use the spread (...) operator jsx/es6 offers

**Comment by acarribasplatag** [comment]
how can you make sortInfo be of type number instead of type string?

**Comment by radubrehar** [comment]
for that column, you specify `type: 'number'`
