### ISSUE TITLE
Example broken on https: Use '//' for facebook CDN

### ISSUE THREAD

**Issue by STRML** [zippyui/react-datagrid#3]
If the user goes to https://zippyui.github.io/react-datagrid/ there is a problem with mixed content. This happens automatically with the HTTPS Everywhere extension.

**Comment by zippyui-react** [comment]
Thanks for spotting that out!

By the way, we like your blog at http://strml.net/ - very nice!
Hope you find the data grid useful :)

**Comment by STRML** [comment]
Thanks!

**Comment by zippyui-react** [comment]
We've just fixed scrolling issues we had on our grid. You may want to visit a demo again to see how well it performs http://zippyui.github.io/react-datagrid/#/examples/column-resizing.
