### ISSUE TITLE
column className property not propagating to cell

### ISSUE THREAD

**Issue by jdeherrera** [zippyui/react-datagrid#39]
The cell component defines a className property, so I would expect a column defined as 
{ name: 'foo', className: 'bar' }
to render a cell with both the default 'z-cell' and 'bar' classes. Basically, it should work like styles do.

The renderCell function in Row/index.jsx just needs to be updated to include column.className when it's building cellProps.

**Comment by koustuvsinha** [comment]
:+1: that would make column styling easier to implement

**Comment by zippyui-react** [comment]
Just implemented this. Totally agree!

column.className should behave similar to column.style. Will release an update very soon

**Comment by zippyui-react** [comment]
Just released 1.1.13 with this feature
