### ISSUE TITLE
hidden column cannot be showed again

### ISSUE THREAD

**Issue by hokkos** [zippyui/react-datagrid#42]
Hi,
thanks for this great widget, but it seems a hidden column cannot be showed again, for example with the sample on this page :
http://zippyui.com/react-datagrid/#/examples/basic
and the code
````javascript
var React    = require('react')
var DataGrid = require('react-datagrid')
var data     = require('../data/1000') //a data array
/**
 * data is an array with 1000 items, like:
 * [
 * 		{ id: 0, index: 1, firstName: 'John', city: 'London', 'email: jon@gmail.com'},
 * 		{ id: 1, .... }
 * ]
 */
var columns = [
	{ name: 'index', title: '#', width: 50 },
	{ name: 'firstName', hidden: true },
	{ name: 'lastName'  },
	{ name: 'city' },
	{ name: 'email' }
]

var App = React.createClass({
	render: function(){
		return <DataGrid
			idProperty='id'
			dataSource={data}
			columns={columns}
			style={{height: 500}}
			//if you don't want to show a column menu to show/hide columns, use
			//withColumnMenu={false}
		/>
	}
})

module.exports = App
````
We cannot click to show show again the firstName column.
Thanks.

**Comment by zippyui-react** [comment]
column.hidden is a controlled prop, so for it to work, you need to specify the `onColumnVisibilityChange` callback prop and update the hidden property accordingly (see https://github.com/zippyui/react-datagrid/blob/master/README.md#column-showinghiding)

If you want the uncontrolled alternative, simply use `defaultHidden: true` instead

**Comment by hokkos** [comment]
Ok, thank, I didn't understand the difference between hidden and defaultHidden.

**Comment by zippyui-react** [comment]
It's just like `value` vs `defaultValue` for React built-in `<input />`
