### ISSUE TITLE
Is dot operator supported, if the name of a column contains dot ?

### ISSUE THREAD

**Issue by seenupatri** [zippyui/react-datagrid#48]
For example, I have the following data 
data:[{
         id:1,
         user:{firstName: 'Seenu', lastName: 'Patri'}
}]

and I want to give colum definition as below
{name: 'user.firstName', title: 'FirstName'},

Does the above snippet works ?

**Comment by radubrehar** [comment]
You can simply specify a column `render` function

```jsx
var columns = [
    {
        name: 'user',
        render: function(user){
            return user.firstName
        }
    }
]
```

**Comment by mthebert-mmd** [comment]
What if you wanted to use both user.firstName and user.lastName in separate columns?  (user.firstName + ' ' + user.lastName would not work in what I need)

**Comment by radubrehar** [comment]
Just add more columns to the columns array.

```jsx
var columns = [
 { name: '...', render: ... },
 { name: '...', render: ... }
]
```
