### ISSUE TITLE
Local serve failing

### ISSUE THREAD

**Issue by koustuvsinha** [zippyui/react-datagrid#5]
After running `npm run build` when I serve by `npm run serve`, the page keeps on loading. On further inspection, the script calls http://192.168.1.2:9090/webpack-dev-server.js, which I think is hardcoded as there is no instruction on setting up the webpack server.

**Comment by koustuvsinha** [comment]
Replaced `192.168.1.2` from `webpack.config.js` and `index.html` to make it working. Should I submit a PR?

**Comment by zippyui-react** [comment]
Thanks for spotting that out! We've forgotten that as we were testing on multiple devices.
Yes, you can submit a PR, but please make sure you only include that change. We want to keep PR clean & focused.
