### ISSUE TITLE
Sorting/filtering data from remote JSON

### ISSUE THREAD

**Issue by EdgarsK** [zippyui/react-datagrid#51]
Can't figure out how to sort and filter remotely fetched data. Fetch once, then sort and/or filter locally. Is there allready such option?

**Comment by radubrehar** [comment]
You can use `onSortChange` and `onFilter` and build a custom `dataSource` url, which should return data sorted/filtered remotely, if that's what you want.

**Comment by EdgarsK** [comment]
No, i know about this option, but thing is that i need exactly the opposite. Fetch large data set (~10000 rows) once and work with it locally.

**Comment by radubrehar** [comment]
Ok. Will come back with an answer soon, it's very easy to accomplish this

**Comment by radubrehar** [comment]
```jsx
var sorty = require('sorty')
var App = React.createClass({
    getInitialState: function(){
        return {
           sortInfo: [],
           filters: null,
           dataSource: function(){ 
                 //... get data and return promise (able)
                 var p = $.ajax(...)
                p.then(function(data){
                    this.setState({
                       dataSource: data
                    })
                }.bind(this))
                return p
            } //or a url
        }
    },
    onSortChange: function(sortInfo){
          if (Array.isArray(this.state.dataSource)){
                this.sortAndFilter(sortInfo, this.state.filters)
          }
    },

    sortAndFilter: function(sortInfo, filters){
       var data = this.state.dataSource
       data = data.filter(.... ) //filter
       sorty(sortInfo, data)   //now sort
      this.setState({dataSource: data)}
   },
    render: function(){
        
        return <DataGrid
            idProperty="id"
            columns={columns}
            onSortChange={this.onSortChange}
            dataSource={this.state.dataSource}
        />
    }
})
```
similar logic for filtering `onFilter` ... call sortAndFilter again

Thanks for raising this up. It definitely should be a one-liner prop on the grid.
We're going to add this in a near future release.

**Comment by radubrehar** [comment]
We've just added that on our roadmap!

**Comment by EdgarsK** [comment]
Thank you, looking forward to integrated version.

**Comment by acarribasplatag** [comment]
How can you sort only one column at a time?
