### ISSUE TITLE
Add Browser Support Table

### ISSUE THREAD

**Issue by aphillipo** [zippyui/react-datagrid#52]
Just wondering if you support IE8.  Unfortunately that's probably a requirement for us.

Ta.

**Comment by radubrehar** [comment]
Right now IE8 is not supported. We support browser with flexbox. But if you give your columns a fixed width (so explicitly specify `column.width` and don't rely on flexing them) and also give grid body&header a proper size, it should be fairly straightforward to make it working. That's the only 2 places flexbox is used: column widths and header&body.

Hope this helps

**Comment by aphillipo** [comment]
Ah no worried.  I've moved over to griddle for now.  React makes it pretty easy to switch in and out of these things so I may be back in the future.  Supporting IE8 is no fun anyway!
