### ISSUE TITLE
Checkbox selection in table cell?

### ISSUE THREAD

**Issue by jamieabc** [zippyui/react-datagrid#54]
Is it possible that a table cell type of click box, and other component able to know which row is elected?

**Comment by jamieabc** [comment]
Table cell can be rendered using custom render method, so checkbox can be rendered without problem, but what about getting which rows is clicked, is there any way to do that?

**Comment by radubrehar** [comment]
You can use the 3rd param of the `column.render` function to know which row you are rendering.
See https://github.com/zippyui/react-datagrid#column-styling

This is how I would implement the click box for a table column. I would add a column.render fn, and inside this I would render a checkbox for example. Since I have access to the row index, I attach an onChange event to the checkbox, and will know which checkbox has changed.

Alternatively, you can also attach an `onRowClick` handler to the grid.

Please update to the latest 1.1.14 version, just published on npm

**Comment by jamieabc** [comment]
Thanks for your response, is it possible that I put checkbox not only in table row but also in table header? Currently existing examples all table headers shows in string format?

**Comment by zippyui-react** [comment]
yes, you can pass any valid reactElement to `column.title`.

The convention is to show `column.title` in the header. If no `column.title`, then show `column.name`, which should be a string. But `column.title` can be anything that React cat render.

**Comment by jamieabc** [comment]
Great, quite flexible design. I just have checkbox on table header. Thanks for your help.

**Comment by jamieabc** [comment]
Another question, is it possible that I click checkbox at header and all checkbox in rows are also clicked? 

Since checkbox other than header row is rendered using render callback function. How can I make other checkbox also clicked by clicking header checkbox?

**Comment by radubrehar** [comment]
You can hold a checked prop in every data object in your grid.  When you check the header, set the checked prop to true in all your objects, then re-render. Don't forget to render column checkbox bound to the value on your checked prop.
```jsx
column.render = function(value, data){
 return <input type="checkbox" value={data.checked} onChange={...} />
//onChange, update the checked prop in data
}
```

**Comment by jamieabc** [comment]
Oh, got it, thanks. That solves my problem.

**Comment by jamieabc** [comment]
For the header checkbox, I now have a react component `CheckBox` as follows:

	class CheckBox extends React.Component {

	  constructor(props) {
		...
	  }

	  handleChange() {
	  	this.setState({
	        	isChecked: !this.state.isChecked
	      }
	    );
	  }

	  render () {
	    return (
	      <div>
	        <input
	          type='checkbox'
	          checked={this.state.isChecked}
	          onChange={this.handleChange}
	        />
	      </div>
	    );
	  }
	}

And for the column render function, I have a custom render function `renderCheckbox` as follows:

	function renderCheckbox (value, data, cellProps)
	{
		let defaultChecked = false;
		 return(
			<input type='checkbox' checked={defaultChecked} onChange={changeFunction} />
		 );
	 }

Now I got a problem, in `CheckBox` component `handleChange()` function, I would like to make other checkbox rows selected if header checkbox is selected, but I don't know to to pass this prop to column render function `renderCheckbox`.

My situation is data came from remote, so how exactly to implement this `changeFunction` such that header checkbox can communicate with row checkboxes?

**Comment by jamieabc** [comment]
Currently I made a DataGrid with horizontal scrollbar and render cell to checkbox in one of the column, I found it hard to click checkbox of last row due to horizontal scrollbar covers the checkbox. Is there any way to fix this?

**Comment by radubrehar** [comment]
Can you post a link to the code?

**Comment by jamieabc** [comment]
It's quite a large repository and not put on github, but I upload a pic of scrollbar cover checkbox at [here](https://github.com/jamieabc/webpack-example/blob/datagrid/pic.png). From dev tool, the scrollbar is cover the last row of checkbox, so currently cannot click checkbox

**Comment by phkavitha** [comment]
@radubrehar , How to rerender the component once all the checked property is set to true. For me, I'm able to set the `checked` property but the component is not getting rendered.
