### ISSUE TITLE
react-datagrid local build but cannot load

### ISSUE THREAD

**Issue by jamieabc** [zippyui/react-datagrid#55]
Just clone repository and use command `npm run build` to generate packed file. Then put generated file *react-datagrid.js* under my directory which also uses webpack. In my *main.js* file include this new generated file as following:

        import DataGrid form './react-datagrid';

And web pack shows error message as follows:

>ERROR in ./app/react-datagrid.js
Module build failed: SyntaxError: /Users/aaron/Documents/workspace/react-flux/webpack/app/react-datagrid.js: Line 3: Did you mean "react"?
  1 | (function webpackUniversalModuleDefinition(root, factory) {
  2 | 	if(typeof exports === 'object' && typeof module === 'object')
\> 3 | 		module.exports = factory(require("React"));
    |                                                                    ^
  4 | 	else if(typeof define === 'function' && define.amd)
  5 | 		define(["React"], factory);
  6 | 	else if(typeof exports === 'object')
    at File.errorWithNode (/Users/aaron/Documents/workspace/react-flux/webpack/node_modules/babel-core/lib/babel/transformation/file/index.js:464:15)
    at check (/Users/aaron/Documents/workspace/react-flux/webpack/node_modules/babel-core/lib/babel/transformation/transformers/validation/react.js:24:18)
    at TraversalPath.CallExpression (/Users/aaron/Documents/workspace/react-flux/webpack/node_modules/babel-core/lib/babel/transformation/transformers/validation/react.js:31:5)
    at TraversalPath.call (/Users/aaron/Documents/workspace/react-flux/webpack/node_modules/babel-core/lib/babel/traversal/path/index.js:928:28)
    at TraversalPath.visit (/Users/aaron/Documents/workspace/react-flux/webpack/node_modules/babel-core/lib/babel/traversal/path/index.js:960:10)
    at TraversalContext.visitMultiple (/Users/aaron/Documents/workspace/react-flux/webpack/node_modules/babel-core/lib/babel/traversal/context.js:70:16)
    at TraversalContext.visit (/Users/aaron/Documents/workspace/react-flux/webpack/node_modules/babel-core/lib/babel/traversal/context.js:100:19)
    at Function.traverse.node (/Users/aaron/Documents/workspace/react-flux/webpack/node_modules/babel-core/lib/babel/traversal/index.js:64:17)
    at TraversalPath.visit (/Users/aaron/Documents/workspace/react-flux/webpack/node_modules/babel-core/lib/babel/traversal/path/index.js:977:28)
    at TraversalContext.visitSingle (/Users/aaron/Documents/workspace/react-flux/webpack/node_modules/babel-core/lib/babel/traversal/context.js:90:12)
 @ ./app/Table.js 22:21-48

I also copy following settings to my *webpack.config.js*

>  externals: {
    'react': 'React'
  },

Is there anything step that I missed?

**Comment by zippyui-react** [comment]
In order to use `react-datagrid` in your project, you'll just have to 
1. `npm i react-datagrid --save'
2. Import the datagrid into your file:
`import DataGrid from 'react-datagrid'
3. Use the DataGrid.

No need to build the grid yourself. You'll want to use `npm run build` only if you want to contribute to the datagrid, and make a build for a new public release. The files generated in `dist` folder are meant to be used in browser `<script>` tags. For use with webpack/npm, `lib/index.js` is the main file being picked.

**Comment by jamieabc** [comment]
Thanks for your response, react-datagrid is an awesome package, since I have some minor different requirement for datatable, I might need to modify it.

And I just put `lib/index.js` into my directory and include the file using `import DataGrid from './react-datagrid`. However, webpack error message as follows:

>ERROR in ./app/react-datagrid.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./PaginationToolbar in /Users/aaron/Documents/workspace/react-flux/webpack/app
 @ ./app/react-datagrid.js 10:44-74

>ERROR in ./app/react-datagrid.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./models/Column in /Users/aaron/Documents/workspace/react-flux/webpack/app
 @ ./app/react-datagrid.js 11:13-39

>ERROR in ./app/react-datagrid.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./PropTypes in /Users/aaron/Documents/workspace/react-flux/webpack/app
 @ ./app/react-datagrid.js 13:16-38

>ERROR in ./app/react-datagrid.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./Wrapper in /Users/aaron/Documents/workspace/react-flux/webpack/app
 @ ./app/react-datagrid.js 14:14-34

>ERROR in ./app/react-datagrid.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./Header in /Users/aaron/Documents/workspace/react-flux/webpack/app
 @ ./app/react-datagrid.js 15:13-32

>ERROR in ./app/react-datagrid.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./ResizeProxy in /Users/aaron/Documents/workspace/react-flux/webpack/app
 @ ./app/react-datagrid.js 18:18-42

>ERROR in ./app/react-datagrid.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./utils/findIndexByName in /Users/aaron/Documents/workspace/react-flux/webpack/app
 @ ./app/react-datagrid.js 20:22-56

>ERROR in ./app/react-datagrid.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./utils/group in /Users/aaron/Documents/workspace/react-flux/webpack/app
 @ ./app/react-datagrid.js 21:12-36

>ERROR in ./app/react-datagrid.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./render/slice in /Users/aaron/Documents/workspace/react-flux/webpack/app
 @ ./app/react-datagrid.js 23:12-37

>ERROR in ./app/react-datagrid.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./render/getTableProps in /Users/aaron/Documents/workspace/react-flux/webpack/app
 @ ./app/react-datagrid.js 24:21-54

>ERROR in ./app/react-datagrid.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./render/getGroupedRows in /Users/aaron/Documents/workspace/react-flux/webpack/app
 @ ./app/react-datagrid.js 25:21-55

>ERROR in ./app/react-datagrid.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./render/renderMenu in /Users/aaron/Documents/workspace/react-flux/webpack/app
 @ ./app/react-datagrid.js 26:17-47

>ERROR in ./app/react-datagrid.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./utils/preventDefault in /Users/aaron/Documents/workspace/react-flux/webpack/app
 @ ./app/react-datagrid.js 28:21-54

>ERROR in ./app/react-datagrid.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./RowSelect in /Users/aaron/Documents/workspace/react-flux/webpack/app
 @ ./app/react-datagrid.js 79:13-35

>ERROR in ./app/react-datagrid.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./ColumnFilter in /Users/aaron/Documents/workspace/react-flux/webpack/app
 @ ./app/react-datagrid.js 79:37-62

>ERROR in ./app/react-datagrid.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./getDefaultProps in /Users/aaron/Documents/workspace/react-flux/webpack/app
 @ ./app/react-datagrid.js 119:21-49

I already install `babel-load` and have `webpck.config.js`  settings of filetype jsx as follows:

>      {
        test: /\.js$/,
        loader: 'babel-loader',
        exclude: [/bower_components/, /node_modules/]
      },

Did I made any mistake?

**Comment by zippyui-react** [comment]
You might want to use DataGrid as is, and wrap it inside a custom component, that configures the grid as you please, since the grid is highly configurable.

I don't understand what you are trying to accomplish with webpack. Are you trying to modify the sources, and copy-paste them in your folder? I suggest you do not use the compiled lib folder, since that is generated from the src folder. Besides, you use `babel-loader`, so you're safe to use the `react-datagrid/src` folder.

**Comment by jamieabc** [comment]
Oh, I got it, using `src` directory will be a good solution. As you suggest, I just copied `react-datagrid/src` into my directory renamed to `datagrid`. By referencing `react-datagrid/index.jsx`, I import  using `import DataGrid from './datagird'`, some error messages as follows:

>ERROR in ./app/Table.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./datagrid in /Users/aaron/Documents/workspace/react-flux/webpack/app
 @ ./app/Table.js 22:16-37

Content of my `Table.js` is quite simple, import directory and use it as follows:

    'use strict';
    import React from 'react';
    import DataGrid from './datagrid';

I compared webpage configuration file and load file and didn't find something different, is there anything else I need to configure?

**Comment by zippyui-react** [comment]
Are you using babel-loader to transpile .jsx files as well?

**Comment by jamieabc** [comment]
yes, my webpack configuration file as follows:

    ...
    module: {
      noParse: [],
      loaders: [
      {
        test: /\.js$/,
        loader: 'babel-loader',
        exclude: [/bower_components/, /node_modules/]
      },
      {
        test: /\.jsx$/,
        loader: 'babel-loader',
        exclude: [/bower_components/, /node_modules/]
      },

**Comment by radubrehar** [comment]
Can you share a git repo so i can have a look?

**Comment by jamieabc** [comment]
Sure, thanks for your help, I am still discovering how to use node & webpack. My directory is [here](https://github.com/jamieabc/webpack-example/tree/datagrid)

**Comment by radubrehar** [comment]
try adding jsx to resolve extensions in webpack.config

**Comment by radubrehar** [comment]
Again, I would rather use the `react-datagrid` package as in npm, and customize it to suit my own needs.

**Comment by jamieabc** [comment]
Yeah, but I would like to play a little bit with the react table, quite interesting, that's why I want to make some modification and see how it works.

**Comment by radubrehar** [comment]
Did adding the jsx to resolve extensions help?

--
http://radubrehar.ro
http://bibliaonline.ro
http://jslog.com

**Comment by jamieabc** [comment]
I include jsx loader in the `webpack.config.js` file, but it same error still happens.

**Comment by jamieabc** [comment]
another question, for pagination, is it possible that customize it to behave similar to gmail. With archive/unarchive botton on top-left, page selection on top-right?

**Comment by radubrehar** [comment]
There is a default PaginationToolbar that looks like in the http://zippyui.com/react-datagrid/#/examples/remote-data-source page. You can use a custom implementation of a paginationtoolbar using the `paginationFactory` prop, which should be a function that can return any React Element.
