### ISSUE TITLE
How about adding a react element into column render function

### ISSUE THREAD

**Issue by jamieabc** [zippyui/react-datagrid#58]
If I want to have a react-bootstrap icon with popover text on each column, since popover text seems easier to use `React.renderComponentToString` to render. And I found that `column.reader` callback function able to return react component.

If I put a React component in `column.render` function, will it cause any problem?

**Comment by radubrehar** [comment]
`column.render` renders any valid React Element. No problem with that.

`React.renderComponentToString` should be used on server/isomorphic rendering. It's not (especially) meant to be used in the browser.
