### ISSUE TITLE
Dependecy Issue in Local Build

### ISSUE THREAD

**Issue by koustuvsinha** [zippyui/react-datagrid#6]
`sorty` and `faker` modules are not specified in package.json

**Comment by zippyui-react** [comment]
They are not required anywhere in the react-datagrid code. Have I missed something?

In the examples site at http://zippyui.github.io/react-datagrid, which is on the `gh-pages` branch we have used those packages, but they are present in https://github.com/zippyui/react-datagrid/blob/gh-pages/package.json
Let us know if we are missing something

**Comment by koustuvsinha** [comment]
Well actually while serving those two packages are giving as not found, thus had to install those packages to make local build running

**Comment by koustuvsinha** [comment]
Ok on fresh install this didn't happen, wierd! Closing PR #7

**Comment by koustuvsinha** [comment]
Closing this issue. Great package btw, would like to suggest and work on several new features :)

**Comment by zippyui-react** [comment]
You are right, we have used those packages in index.jsx. I was only looking in the `src` directory. So please resend the PR, we will accept it.

Great to hear you like the component, please go ahead with feature proposals. We are currently working on remote data integration and remote pagination

**Comment by koustuvsinha** [comment]
Done!
