### ISSUE TITLE
Unable to use react-datagrid

### ISSUE THREAD

**Issue by kyra-diablo** [zippyui/react-datagrid#60]
I have installed it with npm ('npm install react-datagrid --save').
There was no error message and everything looks fine ('npm view react-datagrid version' shows 1.1.14, the package.json of my project has been extended with the correct version of react-datagrid).

But if I add the require('react-datagrid') to any of the files, the watchify (uses browserify) throws the following error:

events.js:85
throw er; // Unhandled 'error' event
^
Error: watch UNKNOWN
at exports._errnoException (util.js:746:11)
at FSEvent.FSWatcher._handle.onchange (fs.js:1157:26)

The npm-debug.log has a bit fore information:

9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1015:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)

**Comment by koustuvsinha** [comment]
seems like some broken package in installation. can you report which version of npm & node you are using? also, try a fresh install and see what happens

**Comment by radubrehar** [comment]
Could you test without watchify and see if everything goes fine?

**Comment by kyra-diablo** [comment]
Version of npm is 2.10.1, node: 0.12.4. A fresh install didn't solve the problem.
Although using browserify only instead of using watchify does work without a problem.

Do you have any known compatibility issue with watchify? What do you suggest to use instead of watchify in case the problem cannot be solved?

**Comment by radubrehar** [comment]
If you're not tied to browserify, you could try webpack. It's really worth it!

**Comment by kyra-diablo** [comment]
Thanks for the tip! 
Webpack turned out be a lot better than watchify and the problem did not appear anymore.

**Comment by radubrehar** [comment]
Great to hear that! Webpack does a great job!
