### ISSUE TITLE
Some data is hidden when rows are grouped

### ISSUE THREAD

**Issue by zhbhun** [zippyui/react-datagrid#62]
![image](https://cloud.githubusercontent.com/assets/1996891/8322237/c6d8eca4-1a64-11e5-9825-337d4353e1bd.png)

**Comment by radubrehar** [comment]
Thanks for bringing this out!
The grouping feature still needs some polish, we're looking into it.

**Comment by davertron** [comment]
Any progress on this? I'm seeing this now too, put up an example page here: http://davertron.github.io/react-datagrid-grouping-bug/

**Comment by radubrehar** [comment]
@zhbhun and @davertron can you please confirm this is fixed in `1.2.14` - thanks @davertron for a good  bug catch!

**Comment by davertron** [comment]
I can confirm that it's fixed for me :+1:

**Comment by zhbhun** [comment]
It's fixed for me.
