### ISSUE TITLE
Header is taking up entire height

### ISSUE THREAD

**Issue by owenconti** [zippyui/react-datagrid#64]
I've added react-datagrid to my project through webpack, and am linking to the index.css found in the /dist folder.

Whenever I render my datagrid, the header is taking up the entire height of the grid. I've gone through everything element that the datagrid renders, and compared the CSS of mine to one of the examples. Everything matches, and I have no external styles that are being applied to any part of the datagrid.

Does anyone have any idea why this may be happening?

![screen shot 2015-06-26 at 10 47 52 am](https://cloud.githubusercontent.com/assets/791222/8382592/dffa62ca-1bf0-11e5-8446-b042f5d5e8e0.png)

**Comment by owenconti** [comment]
Solved. No idea why, but I had to override the 'height: "100%"' property on '.react-datagrid .z-column-header .z-inner' to 'height: auto;'

**Comment by radubrehar** [comment]
We're glad you found a solution. Will look into this and inpect why it happened and make sure there are correct defaults for every case. Thanks!
