### ISSUE TITLE
How to setup table row style

### ISSUE THREAD

**Issue by jamieabc** [zippyui/react-datagrid#66]
Is there any way to setup background color of normal row, cursor hover row, header row, cursor hover row? I know there's is a rowStyle attribute, but it seems not triggered when cursor hover.

Is there any way to modify odd/even row color settings?

**Comment by ycavatars** [comment]
I also have the similar problem and read the code. I found that there's an `mouseOverClassName` prop in your Row component. But I don't know how to set the props. I tried to add `mouseOverClassName` to the line https://github.com/zippyui/react-datagrid/blob/master/dist/react-datagrid.js#L2137 but failed.

Could you help me how to set the mouseOverClassName and other Row props? Thanks.

**Comment by radubrehar** [comment]
We've just released version `1.2.0`, please check it out from npm.

Also, see https://github.com/zippyui/react-datagrid#rows. We've just updated row styling to be more flexible and allow the use-cases described above.

**Comment by radubrehar** [comment]
We've had some issues with the latest releases, so please update to 1.2.11
