### ISSUE TITLE
Mutlirow select AND grouping? 

### ISSUE THREAD

**Issue by mikeerickson** [zippyui/react-datagrid#70]
Is it possible to support both grouping AND mutlirow selection?  I have been banging my head trying to find a solution to support both of these capabilities, but I am coming up empty.

**Comment by radubrehar** [comment]
It's not yet on our supported features list, but it shouldn't be too difficult. Have you got the multiselect working on a non-grouping grid?

**Comment by mikeerickson** [comment]
@radubrehar I have it all working now...

**Comment by radubrehar** [comment]
Glad to hear that. Maybe let us & other users know what solution you found, so it can be useful to someone else as well?

Thanks

**Comment by davertron** [comment]
I'd love to hear how to get grouping and multi-select working together, we're actually thinking of moving away from this project because it seems to be dead and because of some missing features like this.
