### ISSUE TITLE
How do I select text from the table?

### ISSUE THREAD

**Issue by snario** [zippyui/react-datagrid#77]
I just want to be able to copy some text from a cell into my clipboard. `user-select` is set to `none` but changing it to `all` fixes nothing. Any help?

**Comment by jesty** [comment]
Hi, you can override this CSS rule:

```
.react-datagrid .z-row, .react-datagrid .react-datagrid-pagination-toolbar {
    -webkit-user-select: text;
    -moz-user-select: text;
    -ms-user-select: text;
    -o-user-select: text;
    user-select: text;
}
```

but if you select a text you will trigger also a selection event
