### ISSUE TITLE
Only a ReactOwner can have refs.

### ISSUE THREAD

**Issue by cboebel** [zippyui/react-datagrid#82]
Hello -

Just discovered react-datagrid. It's really cool.
I'm playing around with it, and have gotten things like selection and sorting working without a problem. When I added filtering - following what you have on the examples site, I get the following three errors when I click the filter icon for any column.

> Uncaught TypeError: Cannot read property 'firstChild' of undefined

> Uncaught Error: Invariant Violation: removeComponentAsRefFrom(...): Only a ReactOwner can have refs. This usually means that you're trying to remove a ref to a component that doesn't have an owner (that is, was not created inside of another component's `render` method). Try rendering this component inside of a new top-level component which will hold the ref.

> Uncaught TypeError: Cannot read property 'firstChild' of undefined

The code is pretty straightforward. I pull the following code into index.html with a script tag. Everything worked great until I added the filtering code. I am certain that it's my lack of understanding that has lead to this problem. I just don't know what it might be.

Any help is appreciated. Thanks!

Anyhow, here's the code. At this point, I'm just trying things out. I understand that it's not the cleanest code in the universe!

```javascript

var itemHandler=require('./items.js').ItemHandler;
var sorty=require('sorty');
var DataGrid=require('react-datagrid');

var items=new itemHandler();
items.populateItems();

var theOriginalItems=items.getItems();
var columns=items.getColumns();

var theItems=[].concat(theOriginalItems);

var SELECTED_ID=null;
var name='';
var SORT_INFO = [ { name: '_id', dir: 'asc'}];

function sort(arr){
	return sorty(SORT_INFO, arr)
}

console.log(theItems);

theItems=sort(theItems);

var ItemGrid=React.createClass({
  render: function(){
		return (
      <div>
  			<DataGrid
  				idProperty='_id'
  				dataSource={theItems}
  				columns={columns}
          style={{height: 400}}
  				selected={SELECTED_ID}
  				onSelectionChange={this.onSelectionChange}

          sortInfo={SORT_INFO}
  				onSortChange={this.handleSortChange}
  				onColumnOrderChange={this.handleColumnOrderChange}

					onFilter={this.handleFilter}
					liveFilter={true}
        />
        <p>Selected: <b>{name}</b></p>
      </div>
    );
	},
  onSelectionChange: function(newSelectedId, data){
		SELECTED_ID = newSelectedId

		name = SELECTED_ID != null? data.name: 'none'
		this.setState({})
	},
  handleSortChange: function(sortInfo){
    SORT_INFO = sortInfo

    theItems=[].concat(theOriginalItems);
    theItems = sort(theItems)

    this.setState({})
  },
  handleColumnOrderChange: function (index, dropIndex){
    var col = columns[index]
    columns.splice(index, 1) //delete from index, 1 item
    columns.splice(dropIndex, 0, col)
    this.setState({})
  },
	handleFilter: function(column, value, allFilterValues){
			//reset data to original data-array
	    theItems=[].concat(theOriginalItems);

	    //go over all filters and apply them
    	Object.keys(allFilterValues).forEach(function(name){
    		var columnFilter = (allFilterValues[name] + '').toUpperCase()

    		if (columnFilter == ''){
    			return
    		}

    		theItems = theItems.filter(function(item){
    		    if ((item[name] + '').toUpperCase().indexOf(columnFilter) === 0){
    		        return true
    		    }
    		})
    	})

	    this.setState({});
	}
});

React.render(<ItemGrid />, document.getElementById('app'));
```

**Comment by cboebel** [comment]
This just in...

I also receive a variant of one of the above errors when the grid is first rendered:

> Uncaught Error: Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. This usually means that you're trying to add a ref to a component that doesn't have an owner (that is, was not created inside of another component's `render` method). Try rendering this component inside of a new top-level component which will hold the ref.

On selection, I get the following. Selection still works, but generates this error:

> Uncaught TypeError: Cannot read property 'firstChild' of undefined

Sorting also works, but generates errors very similar to those I listed in my initial comment.

I should also point out that I'm using the code in electron (formerly atom-shell). The only build step I have is running the jsx tool to convert the jsx to javascript.

Thanks again.

**Comment by cboebel** [comment]
Solved, although I dont know why. I reinstalled react-datagrid, and all errors went away.

**Comment by radubrehar** [comment]
@cboebel glad to see it sorted out! Enjoy the grid!
