### ISSUE TITLE
Can't sort single columns

### ISSUE THREAD

**Issue by acarribasplatag** [zippyui/react-datagrid#96]
I've been trying to look for information to sort on only one column and I can't find anything, the onSortChange only lets me sort multiple columns.

**Comment by radubrehar** [comment]
`onSortChange` is called with sortInfo, which you provide back to the grid, so you are free to pass in sortInfo for only 1 column. Let me know how it goes.

**Comment by acarribasplatag** [comment]
I do pass sortInfo for only one column but unless you click on one column 3 times to deactivate the sorting, it will sort that one + any other column you click on. 

  handleSortChange: function(info){
    sortInfo = info;
    var newestData = this.state.newData;
    newestData = [].concat(newestData)
    newestData = sort(newestData)
    this.setState({newData : newestData})

    },

**Comment by nikhilk78** [comment]
I also needed this so I did this
If(info.length > 0)
sortInfo = [info[info.length-1]];
else
sortInfo = [];
This way only one column is sorted and even if you change column it works.
Not sure if this is what you need.

**Comment by arrb** [comment]
sorry for the late response, yes this is what I did and fixed the problem. Thank you !

**Comment by srahulprdxn** [comment]
@nikhilk78 Thanks for the code. I modified it a bit to sort the column only in ascending or descending:

```
    if(sortInfo.length > 0) {
      this.SORT_INFO = [sortInfo[sortInfo.length - 1]];
    } else {
      this.SORT_INFO[0].dir = 1;
      // this.SORT_INFO = [];
    }
```
