### ISSUE TITLE
click on header to change sorting order doesn't work on chrome/chromium

### ISSUE THREAD

**Issue by marianoguerra** [zippyui/react-datagrid#98]
hi,

had the problem where trying to click the headers on this example http://zippyui.com/react-datagrid/#/examples/sorting won't change the sort order on chrome and chromium but it will on firefox.

downloaded the code and found the reason, on my machine (and other machines, not sure if all of them) 

on firefox:

* EVENT_NAMES.onMouseDown is onMouseDown
* EVENT_NAMES.onMouseUp is onMouseUp

on chrome:

* EVENT_NAMES.onMouseDown is onTouchStart
* EVENT_NAMES.onMouseUp is onTouchEnd

I happen to have a laptop with touch screen, so I tried touching the header on the screen and it worked, but didn't with the mouse, but still I'm not sure that all other people that reported the problem have a touchscreen.

the easy solution is just to use onMouseDown and onMouseUp explicitly since they will also work for touch (at least on my computer and an Ipad).

**Comment by marianoguerra** [comment]
I can provide a pull request with the proposed fix if you think is the right solution

**Comment by radubrehar** [comment]
Yes, I think we can accept the PR
